### PR TITLE
[Wi-Fi] Enabled both the buttons for 917SoC 2.0 boards

### PR DESCRIPTION
**Pull request by srningap**
* Added BRD4338A folder
* Configured GPIO_11 for BTN1 and added the interrupt handler (IRQ059_Handler)
* Configured GPIO_2 for BTN0 and added the interrupt handler (IRQ021_Handler)

Created a draft PR with the changes required in CSA master https://github.com/project-chip/connectedhomeip/pull/29055

### CODE REVIEW

**Review by rosahay-silabs — CHANGES_REQUESTED** [review]
rename the folder to BRD43xxx to accommodate the fact of using the same files with BRD4338A

**Review by rosahay-silabs — APPROVED** [review]

**Comment by rosahay-silabs** [comment]
> rename the folder to BRD43xxx to accommodate the fact of using the same files with BRD4338A

Team unable to do that since a EFR32 board also have BRD43xxx, moved to maintaining BRD4338A for now

**Review by selissia — APPROVED** [review]

**Comment by mykrupp** [comment]
Does this replace the file rsi_hal_mcu_m4.c in examples/platform/silabs/SiWx917/SiWx917/hal/ ? If so, shouldn't this file be added there?

**Comment by mykrupp** [comment]
OK, can the file from examples/platform/silabs/SiWx917 be deleted then in a follow up PR?

**Comment by srningap** [comment]
> OK, can the file from examples/platform/silabs/SiWx917 be deleted then in a follow up PR?

yes, can be deleted.

**Review by mykrupp — APPROVED** [review]

**Pull request merged**
