### PR TITLE
Moves WIFI dependent code

### PR DESCRIPTION
**Pull request by nipatel-silabs**
#### Problem / Feature
What is being fixed? What is the feature being added? Examples:
* moving files from matter_support to connectedhomeip\src\platform\EFR32

#### Change overview
What's in this PR
cleaning up of wifi files from connectedhomeip\third_party\silabs\matter_support\matter to connectedhomeip\src\platform\EFR32

#### Testing
How was this tested?
* manually tested on mg12 +rs9116

### CODE REVIEW

**Review by mkardous-silabs — CHANGES_REQUESTED** [review]
Temporarily blocking the PR until PRs #35 and #34 are merged.

**Review by jmartinez-silabs — COMMENTED** [review]
Like Mathieu said this depends on the cleanup pr landing first, as you need to move the cleaned up files to CSA repo.

Also
I strongly believe not all those files should be in 
src/platform/EFR32/

In fact, from what I see here i would do the following
move folder /wifi/rs911x/ -> examples/platform/efr32/
/wifi/wf200/ -> examples/platform/efr32
move rest of the folder in wifi/ -> src/platform/EFR32

final result
+/examples/platform/efr32/wifi
+++ /rs911x/
+++ /wf200/


+/src/platform/EFR32/wifi
+++dhcp_client.cpp
+++dhcp_client.h
+++ethernetif.cpp
+++ethernetif.h
+++lwip_netif.cpp
+++wfx_host_events.h
+++wfx_msg.h
+++wfx_notify.cpp
+++wfx_config.h

**Comment by mkardous-silabs** [comment]
@nipatel-silabs what is the status of this PR?

**Comment by mkardous-silabs** [comment]
PR has been stale for a very long time. Closing it.

**Pull request closed without merging**
